services:
  dentistry-backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: dentistry-backend
    volumes:
      - .:/opt
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    entrypoint: bash ./docker/entrypoint.sh server
    restart: always
    networks:
      - dentistry_network
    depends_on:
      dentistry-redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health/" ]
      interval: 5s
      timeout: 3s
      retries: 5

  dentistry-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - dentistry_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  dentistry-frontend:
    hostname: dentistry-frontend
    image: markyvva/dentistry-kcdi:latest
    volumes:
      - ./media:/var/www/media
    depends_on:
      - dentistry-backend
    restart: always
    networks:
      - dentistry_network

  nginx:
    image: nginx:1.17
    hostname: nginx
    container_name: nginx
    depends_on:
      dentistry-backend:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/var/www/media
      - ./static:/var/www/static
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - dentistry_network

networks:
  dentistry_network:
    name: dentistry
    driver: bridge
