# Generated by Django 5.0.4 on 2024-06-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat', models.IntegerField(blank=True, null=True, verbose_name='идентификатор Telegram чата для уведомлений')),
                ('send_to_telegram', models.BooleanField(default=True, verbose_name='отправлять уведомления в Telegram')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='почта для получения уведомлений')),
                ('send_to_email', models.BooleanField(default=True, verbose_name='отправлять уведомления на почту')),
            ],
            options={
                'verbose_name': 'настройки уведомлений',
                'verbose_name_plural': 'настройки уведомлений',
            },
        ),
    ]
