# Generated by Django 5.0.4 on 2024-06-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('job', models.CharField(max_length=300, verbose_name='должность')),
                ('experience', models.CharField(help_text='Продолжите фразу: Опыт работы ...', max_length=300, verbose_name='стаж')),
                ('photo', models.ImageField(upload_to='import/photos', verbose_name='фото')),
                ('about', models.TextField(verbose_name='описание опыта специалиста')),
            ],
            options={
                'verbose_name': 'специалист',
                'verbose_name_plural': 'специалисты',
            },
        ),
    ]
