# Generated by Django 5.0.4 on 2024-06-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(upload_to='media/import/photos', verbose_name='фото'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='имя клиента')),
                ('phone_number', models.CharField(blank=True, max_length=300, verbose_name='номер телефона')),
                ('callback', models.BooleanField(default=False, verbose_name='обратный звонок')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='website.specialist', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
            },
        ),
    ]
