# Generated by Django 5.0.4 on 2024-06-09 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_specialist_photo_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'категория прайс листа',
                'verbose_name_plural': 'категории прайс листа',
            },
        ),
        migrations.CreateModel(
            name='PriceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/import/price', verbose_name='файл прайс листа')),
            ],
            options={
                'verbose_name': 'файл прайс листа',
                'verbose_name_plural': 'файлы прайс листа',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='название услуги')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='website.pricecategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
    ]
