# Generated by Django 5.0.4 on 2024-06-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_pricecategory_pricefile_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='client_problem',
            field=models.TextField(blank=True, verbose_name='проблема клиента'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='carousel_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/import/photos', verbose_name='фото для карусели'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='in_carousel',
            field=models.BooleanField(default=True, verbose_name='отображать в карусели'),
        ),
    ]
