# Generated by Django 5.0.4 on 2024-06-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_notification_client_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CALLBACK', 'Обратный звонок'), ('FREE_CONSULTATION', 'Бесплатная консультация')], default='CALLBACK', max_length=300, verbose_name='тип уведомления'),
        ),
    ]
