# Generated by Django 5.0.4 on 2024-06-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='about',
            field=models.TextField(blank=True, verbose_name='описание опыта специалиста'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='experience',
            field=models.CharField(blank=True, help_text='Продолжите фразу: Опыт работы ...', max_length=300, verbose_name='стаж'),
        ),
    ]
