# Generated by Django 5.0.4 on 2024-06-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_specialist_about_alter_specialist_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='название раздела')),
            ],
            options={
                'verbose_name': 'раздел прайс листа',
                'verbose_name_plural': 'разделы прайс листа',
            },
        ),
        migrations.AlterModelOptions(
            name='pricecategory',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='website.pricecategory', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='price',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='website.pricesection', verbose_name='раздел'),
        ),
        migrations.AddField(
            model_name='pricecategory',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='website.pricesection', verbose_name='раздел'),
        ),
    ]
