# Generated by Django 5.0.6 on 2024-06-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='media/import/service', verbose_name='фото №1')),
                ('about', models.TextField(blank=True, verbose_name='описание')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='media/import/service', verbose_name='фото №2')),
                ('main_directions', models.TextField(blank=True, verbose_name='основные направления')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
    ]
