# Generated by Django 5.0.6 on 2024-06-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='working_hours',
            field=models.CharField(help_text="для размещения информации на нескольких строках, нужно разделить строку знаком ','", max_length=300, verbose_name='часы работы'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='validity',
            field=models.CharField(blank=True, max_length=300, verbose_name='срок действия'),
        ),
    ]
