# Generated by Django 5.0.6 on 2024-08-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_service_carousel_photo_service_in_carousel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='имя клиента')),
                ('phone_number', models.CharField(blank=True, max_length=300, verbose_name='номер телефона')),
                ('feedback', models.TextField(verbose_name='отзыв')),
                ('published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='оценка')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
