# Generated by Django 5.0.6 on 2024-08-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='имя клиента')),
                ('taxpayer_name', models.CharField(blank=True, max_length=300, verbose_name='имя налогоплательщика')),
                ('INN', models.CharField(blank=True, max_length=300, verbose_name='ИНН налогоплательщика')),
                ('reporting_year', models.PositiveSmallIntegerField(blank=True, verbose_name='отчетный год')),
                ('phone_number', models.CharField(blank=True, max_length=300, verbose_name='номер телефона')),
                ('issue_type', models.CharField(choices=[('CLINIC', 'Выдать в клинике'), ('EMAIL', 'Выслать на почту')], max_length=50, verbose_name='вариант получения')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('done', models.BooleanField(default=False, verbose_name='подготовлено')),
            ],
            options={
                'verbose_name': 'заявление',
                'verbose_name_plural': 'заявления',
            },
        ),
    ]
